### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by elraro** [rycus86/docker-arm64v8-debian-qemu#1]
Hello!

Im trying to port a gitlab dockerfile from raspberry pi2 to armv8. I want to use ur docker image, but when i try to launch /bin/bash (just run the image) i get this error:

standard_init_linux.go:178: exec user process caused "no such file or directory"

Thanks!

**Comment by rycus86** [comment]
Hi!

That error - from what I've seen - usually means that your host system isn't compatible with the image's architecture.
Are you trying to run it on a pi2 with `armel`/`armhf` architecture instead of `aarch64`?

If you're looking to use this to build images for `aarch64` (e.g. arm64) on an `x64` host (like Travis agents) then there's one setup step to register the [QEMU](https://github.com/multiarch/qemu-user-static) binary with the kernel:  
`docker run --rm --privileged multiarch/qemu-user-static:register --reset`  
After this the build should be ok (and running /bin/sh too).

Hope this helps!

**Comment by elraro** [comment]
thanks! :)

**Comment by rycus86** [comment]
You're welcome! :)
Closing this issue for now, let me know if you need any more help!
